/* ============================================================
   HISTORY OF WORLD CUP — real_rosters.js
   Loturi reale (jucători reali istorici, nu generați) pentru toate
   combinațiile echipă+an care au participat cu adevărat la turneul
   respectiv (din cele 23 de echipe curate din TEAMS, data.js),
   plus câteva echipe "shadow" (adversari istorici reali în cele 12
   campanii curate din real_fixtures.js). Cheie: "<COD_ECHIPA>_<AN>".
   Fiecare jucător: { name, pos } — pos e una din GK/DF/MF/FW.

   Combinațiile echipă+an fără lot real aici (selectabile teoretic
   în joc, dar care nu au avut loc istoric) folosesc în continuare
   generarea aleatoare de nume din engine.js — vezi generateSquad().
   Sursă: paginile Wikipedia "[an] FIFA World Cup squads", verificate
   încrucișat jucător cu jucător.

   Notă: câțiva jucători sunt scriși cu numele complet (ex. "Ronaldo
   Nazário" în loc de doar "Ronaldo") ca să se potrivească exact cu
   intrarea corespunzătoare din LEGENDS (data.js) — asta declanșează
   boost-ul de "legendă" (rating sporit + bio) în generateSquad().
   ============================================================ */

const REAL_ROSTERS = {

URU_1930: [
    { name: "Enrique Ballestrero", pos: "GK" },
    { name: "Miguel Capuccini", pos: "GK" },
    { name: "Ernesto Mascheroni", pos: "DF" },
    { name: "José Nasazzi", pos: "DF" },
    { name: "Emilio Recoba", pos: "DF" },
    { name: "Domingo Tejera", pos: "DF" },
    { name: "José Leandro Andrade", pos: "MF" },
    { name: "Lorenzo Fernández", pos: "MF" },
    { name: "Álvaro Gestido", pos: "MF" },
    { name: "Ángel Melogno", pos: "MF" },
    { name: "Conduelo Píriz", pos: "MF" },
    { name: "Carlos Riolfo", pos: "MF" },
    { name: "Peregrino Anselmo", pos: "FW" },
    { name: "Juan Carlos Calvo", pos: "FW" },
    { name: "Héctor Castro", pos: "FW" },
    { name: "Pedro Cea", pos: "FW" },
    { name: "Pablo Dorado", pos: "FW" },
    { name: "Santos Iriarte", pos: "FW" },
    { name: "Pedro Petrone", pos: "FW" },
    { name: "Zoilo Saldombide", pos: "FW" },
    { name: "Héctor Scarone", pos: "FW" },
    { name: "Santos Urdinarán", pos: "FW" },
  ],

  BRA_1950: [
    { name: "Barbosa", pos: "GK" },
    { name: "Castilho", pos: "GK" },
    { name: "Augusto", pos: "DF" },
    { name: "Nílton Santos", pos: "DF" },
    { name: "Juvenal", pos: "DF" },
    { name: "Nena", pos: "DF" },
    { name: "Bigode", pos: "DF" },
    { name: "Bauer", pos: "MF" },
    { name: "Danilo Alvim", pos: "MF" },
    { name: "Ely", pos: "MF" },
    { name: "Noronha", pos: "MF" },
    { name: "Rui", pos: "MF" },
    { name: "Friaça", pos: "FW" },
    { name: "Zizinho", pos: "FW" },
    { name: "Ademir", pos: "FW" },
    { name: "Jair", pos: "FW" },
    { name: "Chico", pos: "FW" },
    { name: "Adãozinho", pos: "FW" },
    { name: "Alfredo", pos: "FW" },
    { name: "Baltazar", pos: "FW" },
    { name: "Maneca", pos: "FW" },
    { name: "Rodrigues", pos: "FW" },
  ],

  GER_1954: [
    { name: "Toni Turek", pos: "GK" },
    { name: "Heinz Kubsch", pos: "GK" },
    { name: "Heinz Kwiatkowski", pos: "GK" },
    { name: "Fritz Laband", pos: "DF" },
    { name: "Werner Kohlmeyer", pos: "DF" },
    { name: "Hans Bauer", pos: "DF" },
    { name: "Herbert Erhardt", pos: "DF" },
    { name: "Josef Posipal", pos: "DF" },
    { name: "Werner Liebrich", pos: "DF" },
    { name: "Horst Eckel", pos: "MF" },
    { name: "Karl Mai", pos: "MF" },
    { name: "Paul Mebus", pos: "MF" },
    { name: "Karl-Heinz Metzner", pos: "MF" },
    { name: "Alfred Pfaff", pos: "MF" },
    { name: "Helmut Rahn", pos: "FW" },
    { name: "Max Morlock", pos: "FW" },
    { name: "Bernhard Klodt", pos: "FW" },
    { name: "Ottmar Walter", pos: "FW" },
    { name: "Fritz Walter", pos: "FW" },
    { name: "Richard Herrmann", pos: "FW" },
    { name: "Ulrich Biesinger", pos: "FW" },
    { name: "Hans Schäfer", pos: "FW" },
  ],

  ENG_1966: [
    { name: "Gordon Banks", pos: "GK" },
    { name: "Ron Springett", pos: "GK" },
    { name: "Peter Bonetti", pos: "GK" },
    { name: "George Cohen", pos: "DF" },
    { name: "Ray Wilson", pos: "DF" },
    { name: "Jack Charlton", pos: "DF" },
    { name: "Bobby Moore", pos: "DF" },
    { name: "Jimmy Armfield", pos: "DF" },
    { name: "Gerry Byrne", pos: "DF" },
    { name: "Norman Hunter", pos: "DF" },
    { name: "Nobby Stiles", pos: "MF" },
    { name: "Alan Ball", pos: "MF" },
    { name: "Bobby Charlton", pos: "MF" },
    { name: "Martin Peters", pos: "MF" },
    { name: "Ron Flowers", pos: "MF" },
    { name: "Ian Callaghan", pos: "MF" },
    { name: "George Eastham", pos: "MF" },
    { name: "Jimmy Greaves", pos: "FW" },
    { name: "Geoff Hurst", pos: "FW" },
    { name: "John Connelly", pos: "FW" },
    { name: "Terry Paine", pos: "FW" },
    { name: "Roger Hunt", pos: "FW" },
  ],

  BRA_1970: [
    { name: "Félix", pos: "GK" },
    { name: "Ado", pos: "GK" },
    { name: "Leão", pos: "GK" },
    { name: "Brito", pos: "DF" },
    { name: "Carlos Alberto", pos: "DF" },
    { name: "Marco Antônio", pos: "DF" },
    { name: "Baldocchi", pos: "DF" },
    { name: "Fontana", pos: "DF" },
    { name: "Everaldo", pos: "DF" },
    { name: "Joel Camargo", pos: "DF" },
    { name: "Zé Maria", pos: "DF" },
    { name: "Piazza", pos: "MF" },
    { name: "Clodoaldo", pos: "MF" },
    { name: "Gérson", pos: "MF" },
    { name: "Rivellino", pos: "MF" },
    { name: "Paulo Cézar Caju", pos: "MF" },
    { name: "Jairzinho", pos: "FW" },
    { name: "Tostão", pos: "FW" },
    { name: "Pelé", pos: "FW" },
    { name: "Roberto Miranda", pos: "FW" },
    { name: "Edu", pos: "FW" },
    { name: "Dario", pos: "FW" },
  ],

  ARG_1986: [
    { name: "Luis Islas", pos: "GK" },
    { name: "Nery Pumpido", pos: "GK" },
    { name: "Héctor Zelada", pos: "GK" },
    { name: "José Luis Brown", pos: "DF" },
    { name: "Daniel Passarella", pos: "DF" },
    { name: "Néstor Clausen", pos: "DF" },
    { name: "José Luis Cuciuffo", pos: "DF" },
    { name: "Oscar Garré", pos: "DF" },
    { name: "Julio Olarticoechea", pos: "DF" },
    { name: "Oscar Ruggeri", pos: "DF" },
    { name: "Sergio Batista", pos: "MF" },
    { name: "Ricardo Bochini", pos: "MF" },
    { name: "Claudio Borghi", pos: "MF" },
    { name: "Jorge Burruchaga", pos: "MF" },
    { name: "Diego Maradona", pos: "MF" },
    { name: "Héctor Enrique", pos: "MF" },
    { name: "Ricardo Giusti", pos: "MF" },
    { name: "Carlos Tapia", pos: "MF" },
    { name: "Marcelo Trobbiani", pos: "MF" },
    { name: "Sergio Almirón", pos: "FW" },
    { name: "Jorge Valdano", pos: "FW" },
    { name: "Pedro Pasculli", pos: "FW" },
  ],

  GER_1990: [
    { name: "Bodo Illgner", pos: "GK" },
    { name: "Raimond Aumann", pos: "GK" },
    { name: "Andreas Köpke", pos: "GK" },
    { name: "Stefan Reuter", pos: "DF" },
    { name: "Andreas Brehme", pos: "DF" },
    { name: "Jürgen Kohler", pos: "DF" },
    { name: "Klaus Augenthaler", pos: "DF" },
    { name: "Guido Buchwald", pos: "DF" },
    { name: "Thomas Berthold", pos: "DF" },
    { name: "Paul Steiner", pos: "DF" },
    { name: "Hans Pflügler", pos: "DF" },
    { name: "Pierre Littbarski", pos: "MF" },
    { name: "Thomas Häßler", pos: "MF" },
    { name: "Lothar Matthäus", pos: "MF" },
    { name: "Uwe Bein", pos: "MF" },
    { name: "Andreas Möller", pos: "MF" },
    { name: "Olaf Thon", pos: "MF" },
    { name: "Günter Hermann", pos: "MF" },
    { name: "Rudi Völler", pos: "FW" },
    { name: "Frank Mill", pos: "FW" },
    { name: "Karl-Heinz Riedle", pos: "FW" },
    { name: "Jürgen Klinsmann", pos: "FW" },
  ],

  FRA_1998: [
    { name: "Bernard Lama", pos: "GK" },
    { name: "Fabien Barthez", pos: "GK" },
    { name: "Lionel Charbonnier", pos: "GK" },
    { name: "Vincent Candela", pos: "DF" },
    { name: "Bixente Lizarazu", pos: "DF" },
    { name: "Laurent Blanc", pos: "DF" },
    { name: "Marcel Desailly", pos: "DF" },
    { name: "Lilian Thuram", pos: "DF" },
    { name: "Frank Leboeuf", pos: "DF" },
    { name: "Patrick Vieira", pos: "MF" },
    { name: "Youri Djorkaeff", pos: "MF" },
    { name: "Didier Deschamps", pos: "MF" },
    { name: "Zinédine Zidane", pos: "MF" },
    { name: "Robert Pirès", pos: "MF" },
    { name: "Bernard Diomède", pos: "MF" },
    { name: "Alain Boghossian", pos: "MF" },
    { name: "Emmanuel Petit", pos: "MF" },
    { name: "Christian Karembeu", pos: "MF" },
    { name: "Stéphane Guivarc'h", pos: "FW" },
    { name: "Thierry Henry", pos: "FW" },
    { name: "David Trezeguet", pos: "FW" },
    { name: "Christophe Dugarry", pos: "FW" },
  ],

  JPN_2002: [
    { name: "Yoshikatsu Kawaguchi", pos: "GK" },
    { name: "Seigo Narazaki", pos: "GK" },
    { name: "Hitoshi Sogahata", pos: "GK" },
    { name: "Yutaka Akita", pos: "DF" },
    { name: "Naoki Matsuda", pos: "DF" },
    { name: "Ryuzo Morioka", pos: "DF" },
    { name: "Toshihiro Hattori", pos: "DF" },
    { name: "Kōji Nakata", pos: "DF" },
    { name: "Tsuneyasu Miyamoto", pos: "DF" },
    { name: "Junichi Inamoto", pos: "MF" },
    { name: "Hidetoshi Nakata", pos: "MF" },
    { name: "Hiroaki Morishima", pos: "MF" },
    { name: "Alessandro Santos", pos: "MF" },
    { name: "Takashi Fukunishi", pos: "MF" },
    { name: "Shinji Ono", pos: "MF" },
    { name: "Mitsuo Ogasawara", pos: "MF" },
    { name: "Tomokazu Myojin", pos: "MF" },
    { name: "Kazuyuki Toda", pos: "MF" },
    { name: "Daisuke Ichikawa", pos: "MF" },
    { name: "Akinori Nishizawa", pos: "FW" },
    { name: "Masashi Nakayama", pos: "FW" },
    { name: "Takayuki Suzuki", pos: "FW" },
    { name: "Atsushi Yanagisawa", pos: "FW" },
  ],

  BRA_2002: [
    { name: "Marcos", pos: "GK" },
    { name: "Dida", pos: "GK" },
    { name: "Rogério Ceni", pos: "GK" },
    { name: "Cafu", pos: "DF" },
    { name: "Lúcio", pos: "DF" },
    { name: "Roque Júnior", pos: "DF" },
    { name: "Edmílson", pos: "DF" },
    { name: "Roberto Carlos", pos: "DF" },
    { name: "Juliano Belletti", pos: "DF" },
    { name: "Ânderson Polga", pos: "DF" },
    { name: "Júnior", pos: "DF" },
    { name: "Ricardinho", pos: "MF" },
    { name: "Gilberto Silva", pos: "MF" },
    { name: "Rivaldo", pos: "MF" },
    { name: "Ronaldinho", pos: "MF" },
    { name: "Kléberson", pos: "MF" },
    { name: "Vampeta", pos: "MF" },
    { name: "Juninho Paulista", pos: "MF" },
    { name: "Kaká", pos: "MF" },
    { name: "Ronaldo Nazário", pos: "FW" },
    { name: "Denílson", pos: "FW" },
    { name: "Edílson", pos: "FW" },
    { name: "Luizão", pos: "FW" },
  ],

  GER_2014: [
    { name: "Manuel Neuer", pos: "GK" },
    { name: "Ron-Robert Zieler", pos: "GK" },
    { name: "Roman Weidenfeller", pos: "GK" },
    { name: "Kevin Großkreutz", pos: "DF" },
    { name: "Matthias Ginter", pos: "DF" },
    { name: "Benedikt Höwedes", pos: "DF" },
    { name: "Mats Hummels", pos: "DF" },
    { name: "Erik Durm", pos: "DF" },
    { name: "Philipp Lahm", pos: "DF" },
    { name: "Per Mertesacker", pos: "DF" },
    { name: "Jérôme Boateng", pos: "DF" },
    { name: "Shkodran Mustafi", pos: "DF" },
    { name: "Sami Khedira", pos: "MF" },
    { name: "Bastian Schweinsteiger", pos: "MF" },
    { name: "Mesut Özil", pos: "MF" },
    { name: "Julian Draxler", pos: "MF" },
    { name: "Toni Kroos", pos: "MF" },
    { name: "Mario Götze", pos: "MF" },
    { name: "Christoph Kramer", pos: "MF" },
    { name: "André Schürrle", pos: "FW" },
    { name: "Lukas Podolski", pos: "FW" },
    { name: "Miroslav Klose", pos: "FW" },
    { name: "Thomas Müller", pos: "FW" },
  ],

  ARG_2022: [
    { name: "Franco Armani", pos: "GK" },
    { name: "Gerónimo Rulli", pos: "GK" },
    { name: "Emiliano Martínez", pos: "GK" },
    { name: "Juan Foyth", pos: "DF" },
    { name: "Nicolás Tagliafico", pos: "DF" },
    { name: "Gonzalo Montiel", pos: "DF" },
    { name: "Germán Pezzella", pos: "DF" },
    { name: "Marcos Acuña", pos: "DF" },
    { name: "Cristian Romero", pos: "DF" },
    { name: "Nicolás Otamendi", pos: "DF" },
    { name: "Lisandro Martínez", pos: "DF" },
    { name: "Nahuel Molina", pos: "DF" },
    { name: "Leandro Paredes", pos: "MF" },
    { name: "Rodrigo De Paul", pos: "MF" },
    { name: "Exequiel Palacios", pos: "MF" },
    { name: "Thiago Almada", pos: "MF" },
    { name: "Papu Gómez", pos: "MF" },
    { name: "Guido Rodríguez", pos: "MF" },
    { name: "Alexis Mac Allister", pos: "MF" },
    { name: "Enzo Fernández", pos: "MF" },
    { name: "Julián Álvarez", pos: "FW" },
    { name: "Lionel Messi", pos: "FW" },
    { name: "Ángel Di María", pos: "FW" },
    { name: "Ángel Correa", pos: "FW" },
    { name: "Paulo Dybala", pos: "FW" },
    { name: "Lautaro Martínez", pos: "FW" },
  ],

ARG_1930: [
    { name: "Ángel Bossio", pos: "GK" },
    { name: "Juan Botasso", pos: "GK" },
    { name: "Alberto Chividini", pos: "DF" },
    { name: "José Della Torre", pos: "DF" },
    { name: "Ramón Muttis", pos: "DF" },
    { name: "Fernando Paternoster", pos: "DF" },
    { name: "Edmundo Piaggio", pos: "DF" },
    { name: "Juan Evaristo", pos: "MF" },
    { name: "Luis Monti", pos: "MF" },
    { name: "Rodolfo Orlandini", pos: "MF" },
    { name: "Pedro Arico Suárez", pos: "MF" },
    { name: "Adolfo Zumelzú", pos: "MF" },
    { name: "Roberto Cherro", pos: "FW" },
    { name: "Attilio Demaría", pos: "FW" },
    { name: "Mario Evaristo", pos: "FW" },
    { name: "Manuel Ferreira", pos: "FW" },
    { name: "Natalio Perinetti", pos: "FW" },
    { name: "Carlos Peucelle", pos: "FW" },
    { name: "Alejandro Scopelli", pos: "FW" },
    { name: "Carlos Spadaro", pos: "FW" },
    { name: "Guillermo Stábile", pos: "FW" },
    { name: "Francisco Varallo", pos: "FW" },
  ],

  BRA_1930: [
    { name: "Joel", pos: "GK" },
    { name: "Velloso", pos: "GK" },
    { name: "Brilhante", pos: "DF" },
    { name: "Fausto", pos: "DF" },
    { name: "Hermógenes", pos: "DF" },
    { name: "Itália", pos: "DF" },
    { name: "Zé Luiz", pos: "DF" },
    { name: "Fernando", pos: "MF" },
    { name: "Fortes", pos: "MF" },
    { name: "Ivan Mariz", pos: "MF" },
    { name: "Oscarino", pos: "MF" },
    { name: "Pamplona", pos: "MF" },
    { name: "Araken", pos: "FW" },
    { name: "Benedicto", pos: "FW" },
    { name: "Carvalho Leite", pos: "FW" },
    { name: "Manoelzinho", pos: "FW" },
    { name: "Moderato", pos: "FW" },
    { name: "Nilo", pos: "FW" },
    { name: "Poly", pos: "FW" },
    { name: "Preguinho", pos: "FW" },
    { name: "Russinho", pos: "FW" },
    { name: "Teóphilo", pos: "FW" },
  ],

  FRA_1930: [
    { name: "André Tassin", pos: "GK" },
    { name: "Alex Thépot", pos: "GK" },
    { name: "Numa Andoire", pos: "DF" },
    { name: "Marcel Capelle", pos: "DF" },
    { name: "Jean Laurent", pos: "DF" },
    { name: "Étienne Mattler", pos: "DF" },
    { name: "Augustin Chantrel", pos: "MF" },
    { name: "Edmond Delfour", pos: "MF" },
    { name: "Célestin Delmer", pos: "MF" },
    { name: "Alexandre Villaplane", pos: "MF" },
    { name: "Marcel Langiller", pos: "FW" },
    { name: "Lucien Laurent", pos: "FW" },
    { name: "Ernest Libérati", pos: "FW" },
    { name: "André Maschinot", pos: "FW" },
    { name: "Marcel Pinel", pos: "FW" },
    { name: "Émile Veinante", pos: "FW" },
  ],

  BEL_1930: [
    { name: "Arnold Badjou", pos: "GK" },
    { name: "Jean De Bie", pos: "GK" },
    { name: "Henri De Deken", pos: "DF" },
    { name: "Nicolas Hoydonckx", pos: "DF" },
    { name: "Théodore Nouwens", pos: "DF" },
    { name: "Alexis Chantraine", pos: "MF" },
    { name: "Jean De Clercq", pos: "MF" },
    { name: "Gérard Delbeke", pos: "MF" },
    { name: "August Hellemans", pos: "MF" },
    { name: "Pierre Braine", pos: "MF" },
    { name: "Ferdinand Adams", pos: "FW" },
    { name: "Jan Diddens", pos: "FW" },
    { name: "Jacques Moeschal", pos: "FW" },
    { name: "André Saeys", pos: "FW" },
    { name: "Louis Versyp", pos: "FW" },
    { name: "Bernard Voorhoof", pos: "FW" },
  ],

  MEX_1930: [
    { name: "Óscar Bonfiglio", pos: "GK" },
    { name: "Isidoro Sota", pos: "GK" },
    { name: "Rafael Garza Gutiérrez", pos: "DF" },
    { name: "Francisco Garza Gutiérrez", pos: "DF" },
    { name: "Manuel Rosas", pos: "DF" },
    { name: "Efraín Amézcua", pos: "MF" },
    { name: "Juan Carreño", pos: "MF" },
    { name: "Raymundo Rodríguez", pos: "MF" },
    { name: "Felipe Rosas", pos: "MF" },
    { name: "Alfredo Sánchez", pos: "MF" },
    { name: "Jesús Castro", pos: "FW" },
    { name: "Roberto Gayón", pos: "FW" },
    { name: "Hilario López", pos: "FW" },
    { name: "Dionisio Mejía", pos: "FW" },
    { name: "Felipe Olivares", pos: "FW" },
    { name: "Luis Pérez", pos: "FW" },
    { name: "José Ruíz", pos: "FW" },
  ],

  USA_1930: [
    { name: "Jimmy Douglas", pos: "GK" },
    { name: "George Moorhouse", pos: "DF" },
    { name: "Frank Vaughn", pos: "DF" },
    { name: "Alexander Wood", pos: "DF" },
    { name: "Andy Auld", pos: "MF" },
    { name: "Jimmy Gallagher", pos: "MF" },
    { name: "Philip Slone", pos: "MF" },
    { name: "Mike Bookie", pos: "FW" },
    { name: "Jim Brown", pos: "FW" },
    { name: "Tom Florie", pos: "FW" },
    { name: "James Gentle", pos: "FW" },
    { name: "Billy Gonsalves", pos: "FW" },
    { name: "Bart McGhee", pos: "FW" },
    { name: "Arnie Oliver", pos: "FW" },
    { name: "Bert Patenaude", pos: "FW" },
    { name: "Raphael Tracey", pos: "FW" },
  ],

  PER_1930: [
    { name: "Jorge Pardón", pos: "GK" },
    { name: "Juan Valdivieso", pos: "GK" },
    { name: "Mario de las Casas", pos: "DF" },
    { name: "Arturo Fernández", pos: "DF" },
    { name: "Antonio Maquilón", pos: "DF" },
    { name: "Alberto Soria", pos: "DF" },
    { name: "Eduardo Astengo", pos: "MF" },
    { name: "Carlos Cillóniz", pos: "MF" },
    { name: "Alberto Denegri", pos: "MF" },
    { name: "Plácido Galindo", pos: "MF" },
    { name: "Domingo García", pos: "MF" },
    { name: "Julio Quintana", pos: "MF" },
    { name: "José María Lavalle", pos: "FW" },
    { name: "Julio Lores", pos: "FW" },
    { name: "Demetrio Neyra", pos: "FW" },
    { name: "Pablo Pacheco", pos: "FW" },
    { name: "Lizardo Rodríguez Nue", pos: "FW" },
    { name: "Jorge Sarmiento", pos: "FW" },
    { name: "Luis de Souza", pos: "FW" },
    { name: "Alejandro Villanueva", pos: "FW" },
  ],

  ROU_1930: [
    { name: "Ion Lăpușneanu", pos: "GK" },
    { name: "Samuel Zauber", pos: "GK" },
    { name: "Rudolf Bürger", pos: "DF" },
    { name: "Iosif Czako", pos: "DF" },
    { name: "Adalbert Steiner", pos: "DF" },
    { name: "Emerich Vogl", pos: "DF" },
    { name: "Ștefan Barbu", pos: "MF" },
    { name: "Alfred Eisenbeisser", pos: "MF" },
    { name: "László Raffinsky", pos: "MF" },
    { name: "Corneliu Robe", pos: "MF" },
    { name: "Constantin Stanciu", pos: "MF" },
    { name: "Adalbert Deșu", pos: "FW" },
    { name: "Nicolae Kovács", pos: "FW" },
    { name: "Ilie Subășeanu", pos: "FW" },
    { name: "Rudolf Wetzer", pos: "FW" },
  ],

  YUG_1930: [
    { name: "Milovan Jakšić", pos: "GK" },
    { name: "Milan Stojanović", pos: "GK" },
    { name: "Milutin Ivković", pos: "DF" },
    { name: "Dragoslav Mihajlović", pos: "DF" },
    { name: "Dragomir Tošić", pos: "DF" },
    { name: "Milorad Arsenijević", pos: "MF" },
    { name: "Momčilo Đokić", pos: "MF" },
    { name: "Branislav Hrnjiček", pos: "MF" },
    { name: "Teofilo Spasojević", pos: "MF" },
    { name: "Ljubiša Stefanović", pos: "MF" },
    { name: "Ivan Bek", pos: "FW" },
    { name: "Blagoje Marjanović", pos: "FW" },
    { name: "Božidar Marković", pos: "FW" },
    { name: "Dragutin Najdanović", pos: "FW" },
    { name: "Branislav Sekulić", pos: "FW" },
    { name: "Aleksandar Tirnanić", pos: "FW" },
    { name: "Đorđe Vujadinović", pos: "FW" },
  ],

  ITA_1934: [
    { name: "Luigi Allemandi", pos: "DF" },
    { name: "Pietro Arcari", pos: "FW" },
    { name: "Luigi Bertolini", pos: "MF" },
    { name: "Felice Borel", pos: "FW" },
    { name: "Umberto Caligaris", pos: "DF" },
    { name: "Armando Castellazzi", pos: "MF" },
    { name: "Giuseppe Cavanna", pos: "GK" },
    { name: "Gianpiero Combi", pos: "GK" },
    { name: "Attilio Demaria", pos: "FW" },
    { name: "Giovanni Ferrari", pos: "FW" },
    { name: "Attilio Ferraris", pos: "MF" },
    { name: "Enrique Guaita", pos: "FW" },
    { name: "Anfilogino Guarisi", pos: "FW" },
    { name: "Guido Masetti", pos: "GK" },
    { name: "Giuseppe Meazza", pos: "MF" },
    { name: "Luis Monti", pos: "MF" },
    { name: "Eraldo Monzeglio", pos: "DF" },
    { name: "Raimundo Orsi", pos: "FW" },
    { name: "Mario Pizziolo", pos: "MF" },
    { name: "Virginio Rosetta", pos: "DF" },
    { name: "Angelo Schiavio", pos: "FW" },
    { name: "Mario Varglien", pos: "MF" },
  ],

  GER_1934: [
    { name: "Ernst Albrecht", pos: "MF" },
    { name: "Jakob Bender", pos: "MF" },
    { name: "Fritz Buchloh", pos: "GK" },
    { name: "Willy Busch", pos: "DF" },
    { name: "Edmund Conen", pos: "FW" },
    { name: "Franz Dienert", pos: "FW" },
    { name: "Rudolf Gramlich", pos: "MF" },
    { name: "Sigmund Haringer", pos: "DF" },
    { name: "Matthias Heidemann", pos: "FW" },
    { name: "Karl Hohmann", pos: "MF" },
    { name: "Hans Jakob", pos: "GK" },
    { name: "Paul Janes", pos: "DF" },
    { name: "Stanislaus Kobierski", pos: "FW" },
    { name: "Willibald Kreß", pos: "GK" },
    { name: "Ernst Lehner", pos: "FW" },
    { name: "Reinhold Münzenberg", pos: "DF" },
    { name: "Rudolf Noack", pos: "FW" },
    { name: "Hans Schwartz", pos: "DF" },
    { name: "Otto Siffling", pos: "FW" },
    { name: "Josef Streb", pos: "FW" },
    { name: "Fritz Szepan", pos: "FW" },
    { name: "Paul Zielinski", pos: "MF" },
  ],

  TCH_1934: [
    { name: "Jaroslav Bouček", pos: "MF" },
    { name: "Jaroslav Burgr", pos: "DF" },
    { name: "Štefan Čambal", pos: "MF" },
    { name: "Josef Čtyřoký", pos: "DF" },
    { name: "Ferdinand Daučík", pos: "DF" },
    { name: "František Junek", pos: "FW" },
    { name: "Géza Kalocsay", pos: "FW" },
    { name: "Vlastimil Kopecký", pos: "MF" },
    { name: "Josef Košťálek", pos: "MF" },
    { name: "Rudolf Krčil", pos: "MF" },
    { name: "Oldřich Nejedlý", pos: "FW" },
    { name: "Čestmír Patzel", pos: "GK" },
    { name: "František Plánička", pos: "GK" },
    { name: "Antonín Puč", pos: "FW" },
    { name: "Josef Silný", pos: "FW" },
    { name: "Adolf Šimperský", pos: "MF" },
    { name: "Jiří Sobotka", pos: "FW" },
    { name: "Erich Srbek", pos: "FW" },
    { name: "František Šterc", pos: "FW" },
    { name: "František Svoboda", pos: "FW" },
    { name: "Antonín Vodička", pos: "MF" },
    { name: "Ladislav Ženíšek", pos: "DF" },
  ],

  AUT_1934: [
    { name: "Josef Bican", pos: "FW" },
    { name: "Georg Braun", pos: "FW" },
    { name: "Franz Cisar", pos: "DF" },
    { name: "Friederich Franzl", pos: "GK" },
    { name: "Josef Hassmann", pos: "FW" },
    { name: "Leopold Hofmann", pos: "MF" },
    { name: "Johann Horvath", pos: "FW" },
    { name: "Anton Janda", pos: "DF" },
    { name: "Matthias Kaburek", pos: "FW" },
    { name: "Peter Platzer", pos: "GK" },
    { name: "Rudolf Raftl", pos: "GK" },
    { name: "Anton Schall", pos: "FW" },
    { name: "Willibald Schmaus", pos: "DF" },
    { name: "Karl Sesta", pos: "DF" },
    { name: "Matthias Sindelar", pos: "FW" },
    { name: "Josef Smistik", pos: "MF" },
    { name: "Josef Stroh", pos: "FW" },
    { name: "Johann Urbanek", pos: "MF" },
    { name: "Rudolf Viertl", pos: "FW" },
    { name: "Franz Wagner", pos: "MF" },
    { name: "Hans Walzhofer", pos: "FW" },
    { name: "Karl Zischek", pos: "FW" },
  ],

  ESP_1934: [
    { name: "Crisant Bosch", pos: "MF" },
    { name: "Campanal I", pos: "FW" },
    { name: "Chacho", pos: "FW" },
    { name: "Leonardo Cilaurren", pos: "MF" },
    { name: "Ciriaco", pos: "DF" },
    { name: "Fede", pos: "MF" },
    { name: "Guillermo Gorostiza", pos: "FW" },
    { name: "Hilario", pos: "MF" },
    { name: "José Iraragorri", pos: "FW" },
    { name: "Lafuente", pos: "FW" },
    { name: "Isidro Lángara", pos: "FW" },
    { name: "Simón Lecue", pos: "MF" },
    { name: "Martín Marculeta", pos: "MF" },
    { name: "Luis Marín Sabater", pos: "FW" },
    { name: "José Muguerza", pos: "MF" },
    { name: "Juan José Nogués", pos: "GK" },
    { name: "Jacinto Quincoces", pos: "DF" },
    { name: "Luis Regueiro", pos: "FW" },
    { name: "Pedro Solé", pos: "MF" },
    { name: "Martí Ventolrà", pos: "MF" },
    { name: "Ramón Zabalo", pos: "DF" },
    { name: "Ricardo Zamora", pos: "GK" },
  ],

  SWE_1934: [
    { name: "Ernst Andersson", pos: "MF" },
    { name: "Otto Andersson", pos: "DF" },
    { name: "Sven Andersson", pos: "DF" },
    { name: "Nils Axelsson", pos: "DF" },
    { name: "Lennart Bunke", pos: "FW" },
    { name: "Rune Carlsson", pos: "MF" },
    { name: "Victor Carlund", pos: "MF" },
    { name: "Gösta Dunker", pos: "FW" },
    { name: "Ragnar Gustavsson", pos: "FW" },
    { name: "Carl-Erik Holmberg", pos: "FW" },
    { name: "Sture Hult", pos: "GK" },
    { name: "Gunnar Jansson", pos: "FW" },
    { name: "Sven Jonasson", pos: "FW" },
    { name: "Tore Keller", pos: "FW" },
    { name: "Knut Kroon", pos: "FW" },
    { name: "Harry Lundahl", pos: "FW" },
    { name: "Gunnar Olsson", pos: "FW" },
    { name: "Anders Rydberg", pos: "GK" },
    { name: "Nils Rosén", pos: "MF" },
    { name: "Arvid Thörn", pos: "FW" },
    { name: "Eivar Widlund", pos: "GK" },
  ],

  HUN_1934: [
    { name: "István Avar", pos: "FW" },
    { name: "Sándor Bíró", pos: "DF" },
    { name: "János Dudás", pos: "MF" },
    { name: "Gyula Futó", pos: "DF" },
    { name: "József Háda", pos: "GK" },
    { name: "Tibor Kemény", pos: "FW" },
    { name: "Gyula Lázár", pos: "MF" },
    { name: "Imre Markos", pos: "FW" },
    { name: "István Palotás", pos: "MF" },
    { name: "Gyula Polgár", pos: "MF" },
    { name: "György Sárosi", pos: "FW" },
    { name: "Rezső Somlai", pos: "MF" },
    { name: "László Sternberg", pos: "DF" },
    { name: "Antal Szabó", pos: "GK" },
    { name: "Gábor P. Szabó", pos: "FW" },
    { name: "Antal Szalay", pos: "MF" },
    { name: "György Szűcs", pos: "MF" },
    { name: "István Tamássy", pos: "FW" },
    { name: "Pál Teleki", pos: "FW" },
    { name: "Géza Toldi", pos: "FW" },
    { name: "József Vágó", pos: "DF" },
    { name: "Jenő Vincze", pos: "FW" },
  ],

  NED_1934: [
    { name: "Wim Anderiesen", pos: "MF" },
    { name: "Beb Bakhuys", pos: "FW" },
    { name: "Jan Graafland", pos: "FW" },
    { name: "Leo Halle", pos: "GK" },
    { name: "Wim Langendaal", pos: "FW" },
    { name: "Kees Mijnders", pos: "FW" },
    { name: "Jaap Mol", pos: "FW" },
