/* ============================================================
   HISTORY OF WORLD CUP — real_rosters.js
   Loturi reale (jucători reali istorici, nu generați) pentru cele
   12 campanii istorice curate din real_fixtures.js. Cheie identică:
   "<COD_ECHIPA>_<AN>". Fiecare jucător: { name, pos } — pos e una
   din GK/DF/MF/FW.

   Restul combinațiilor echipă+an (fără lot real aici) folosesc în
   continuare generarea aleatoare de nume din engine.js — vezi
   generateSquad(). Sursă: paginile Wikipedia "[an] FIFA World Cup
   squads", verificate încrucișat jucător cu jucător.

   Notă: câțiva jucători sunt scriși cu numele complet (ex. "Ronaldo
   Nazário" în loc de doar "Ronaldo") ca să se potrivească exact cu
   intrarea corespunzătoare din LEGENDS (data.js) — asta declanșează
   boost-ul de "legendă" (rating sporit + bio) în generateSquad().
   ============================================================ */

const REAL_ROSTERS = {

  URU_1930: [
    { name: "Enrique Ballestrero", pos: "GK" },
    { name: "Miguel Capuccini", pos: "GK" },
    { name: "Ernesto Mascheroni", pos: "DF" },
    { name: "José Nasazzi", pos: "DF" },
    { name: "Emilio Recoba", pos: "DF" },
    { name: "Domingo Tejera", pos: "DF" },
    { name: "José Leandro Andrade", pos: "MF" },
    { name: "Lorenzo Fernández", pos: "MF" },
    { name: "Álvaro Gestido", pos: "MF" },
    { name: "Ángel Melogno", pos: "MF" },
    { name: "Conduelo Píriz", pos: "MF" },
    { name: "Carlos Riolfo", pos: "MF" },
    { name: "Peregrino Anselmo", pos: "FW" },
    { name: "Juan Carlos Calvo", pos: "FW" },
    { name: "Héctor Castro", pos: "FW" },
    { name: "Pedro Cea", pos: "FW" },
    { name: "Pablo Dorado", pos: "FW" },
    { name: "Santos Iriarte", pos: "FW" },
    { name: "Pedro Petrone", pos: "FW" },
    { name: "Zoilo Saldombide", pos: "FW" },
    { name: "Héctor Scarone", pos: "FW" },
    { name: "Santos Urdinarán", pos: "FW" },
  ],

  BRA_1950: [
    { name: "Barbosa", pos: "GK" },
    { name: "Castilho", pos: "GK" },
    { name: "Augusto", pos: "DF" },
    { name: "Nílton Santos", pos: "DF" },
    { name: "Juvenal", pos: "DF" },
    { name: "Nena", pos: "DF" },
    { name: "Bigode", pos: "DF" },
    { name: "Bauer", pos: "MF" },
    { name: "Danilo Alvim", pos: "MF" },
    { name: "Ely", pos: "MF" },
    { name: "Noronha", pos: "MF" },
    { name: "Rui", pos: "MF" },
    { name: "Friaça", pos: "FW" },
    { name: "Zizinho", pos: "FW" },
    { name: "Ademir", pos: "FW" },
    { name: "Jair", pos: "FW" },
    { name: "Chico", pos: "FW" },
    { name: "Adãozinho", pos: "FW" },
    { name: "Alfredo", pos: "FW" },
    { name: "Baltazar", pos: "FW" },
    { name: "Maneca", pos: "FW" },
    { name: "Rodrigues", pos: "FW" },
  ],

  GER_1954: [
    { name: "Toni Turek", pos: "GK" },
    { name: "Heinz Kubsch", pos: "GK" },
    { name: "Heinz Kwiatkowski", pos: "GK" },
    { name: "Fritz Laband", pos: "DF" },
    { name: "Werner Kohlmeyer", pos: "DF" },
    { name: "Hans Bauer", pos: "DF" },
    { name: "Herbert Erhardt", pos: "DF" },
    { name: "Josef Posipal", pos: "DF" },
    { name: "Werner Liebrich", pos: "DF" },
    { name: "Horst Eckel", pos: "MF" },
    { name: "Karl Mai", pos: "MF" },
    { name: "Paul Mebus", pos: "MF" },
    { name: "Karl-Heinz Metzner", pos: "MF" },
    { name: "Alfred Pfaff", pos: "MF" },
    { name: "Helmut Rahn", pos: "FW" },
    { name: "Max Morlock", pos: "FW" },
    { name: "Bernhard Klodt", pos: "FW" },
    { name: "Ottmar Walter", pos: "FW" },
    { name: "Fritz Walter", pos: "FW" },
    { name: "Richard Herrmann", pos: "FW" },
    { name: "Ulrich Biesinger", pos: "FW" },
    { name: "Hans Schäfer", pos: "FW" },
  ],

  ENG_1966: [
    { name: "Gordon Banks", pos: "GK" },
    { name: "Ron Springett", pos: "GK" },
    { name: "Peter Bonetti", pos: "GK" },
    { name: "George Cohen", pos: "DF" },
    { name: "Ray Wilson", pos: "DF" },
    { name: "Jack Charlton", pos: "DF" },
    { name: "Bobby Moore", pos: "DF" },
    { name: "Jimmy Armfield", pos: "DF" },
    { name: "Gerry Byrne", pos: "DF" },
    { name: "Norman Hunter", pos: "DF" },
    { name: "Nobby Stiles", pos: "MF" },
    { name: "Alan Ball", pos: "MF" },
    { name: "Bobby Charlton", pos: "MF" },
    { name: "Martin Peters", pos: "MF" },
    { name: "Ron Flowers", pos: "MF" },
    { name: "Ian Callaghan", pos: "MF" },
    { name: "George Eastham", pos: "MF" },
    { name: "Jimmy Greaves", pos: "FW" },
    { name: "Geoff Hurst", pos: "FW" },
    { name: "John Connelly", pos: "FW" },
    { name: "Terry Paine", pos: "FW" },
    { name: "Roger Hunt", pos: "FW" },
  ],

  BRA_1970: [
    { name: "Félix", pos: "GK" },
    { name: "Ado", pos: "GK" },
    { name: "Leão", pos: "GK" },
    { name: "Brito", pos: "DF" },
    { name: "Carlos Alberto", pos: "DF" },
    { name: "Marco Antônio", pos: "DF" },
    { name: "Baldocchi", pos: "DF" },
    { name: "Fontana", pos: "DF" },
    { name: "Everaldo", pos: "DF" },
    { name: "Joel Camargo", pos: "DF" },
    { name: "Zé Maria", pos: "DF" },
    { name: "Piazza", pos: "MF" },
    { name: "Clodoaldo", pos: "MF" },
    { name: "Gérson", pos: "MF" },
    { name: "Rivellino", pos: "MF" },
    { name: "Paulo Cézar Caju", pos: "MF" },
    { name: "Jairzinho", pos: "FW" },
    { name: "Tostão", pos: "FW" },
    { name: "Pelé", pos: "FW" },
    { name: "Roberto Miranda", pos: "FW" },
    { name: "Edu", pos: "FW" },
    { name: "Dario", pos: "FW" },
  ],

  ARG_1986: [
    { name: "Luis Islas", pos: "GK" },
    { name: "Nery Pumpido", pos: "GK" },
    { name: "Héctor Zelada", pos: "GK" },
    { name: "José Luis Brown", pos: "DF" },
    { name: "Daniel Passarella", pos: "DF" },
    { name: "Néstor Clausen", pos: "DF" },
    { name: "José Luis Cuciuffo", pos: "DF" },
    { name: "Oscar Garré", pos: "DF" },
    { name: "Julio Olarticoechea", pos: "DF" },
    { name: "Oscar Ruggeri", pos: "DF" },
    { name: "Sergio Batista", pos: "MF" },
    { name: "Ricardo Bochini", pos: "MF" },
    { name: "Claudio Borghi", pos: "MF" },
    { name: "Jorge Burruchaga", pos: "MF" },
    { name: "Diego Maradona", pos: "MF" },
    { name: "Héctor Enrique", pos: "MF" },
    { name: "Ricardo Giusti", pos: "MF" },
    { name: "Carlos Tapia", pos: "MF" },
    { name: "Marcelo Trobbiani", pos: "MF" },
    { name: "Sergio Almirón", pos: "FW" },
    { name: "Jorge Valdano", pos: "FW" },
    { name: "Pedro Pasculli", pos: "FW" },
  ],

  GER_1990: [
    { name: "Bodo Illgner", pos: "GK" },
    { name: "Raimond Aumann", pos: "GK" },
    { name: "Andreas Köpke", pos: "GK" },
    { name: "Stefan Reuter", pos: "DF" },
    { name: "Andreas Brehme", pos: "DF" },
    { name: "Jürgen Kohler", pos: "DF" },
    { name: "Klaus Augenthaler", pos: "DF" },
    { name: "Guido Buchwald", pos: "DF" },
    { name: "Thomas Berthold", pos: "DF" },
    { name: "Paul Steiner", pos: "DF" },
    { name: "Hans Pflügler", pos: "DF" },
    { name: "Pierre Littbarski", pos: "MF" },
    { name: "Thomas Häßler", pos: "MF" },
    { name: "Lothar Matthäus", pos: "MF" },
    { name: "Uwe Bein", pos: "MF" },
    { name: "Andreas Möller", pos: "MF" },
    { name: "Olaf Thon", pos: "MF" },
    { name: "Günter Hermann", pos: "MF" },
    { name: "Rudi Völler", pos: "FW" },
    { name: "Frank Mill", pos: "FW" },
    { name: "Karl-Heinz Riedle", pos: "FW" },
    { name: "Jürgen Klinsmann", pos: "FW" },
  ],

  FRA_1998: [
    { name: "Bernard Lama", pos: "GK" },
    { name: "Fabien Barthez", pos: "GK" },
    { name: "Lionel Charbonnier", pos: "GK" },
    { name: "Vincent Candela", pos: "DF" },
    { name: "Bixente Lizarazu", pos: "DF" },
    { name: "Laurent Blanc", pos: "DF" },
    { name: "Marcel Desailly", pos: "DF" },
    { name: "Lilian Thuram", pos: "DF" },
    { name: "Frank Leboeuf", pos: "DF" },
    { name: "Patrick Vieira", pos: "MF" },
    { name: "Youri Djorkaeff", pos: "MF" },
    { name: "Didier Deschamps", pos: "MF" },
    { name: "Zinédine Zidane", pos: "MF" },
    { name: "Robert Pirès", pos: "MF" },
    { name: "Bernard Diomède", pos: "MF" },
    { name: "Alain Boghossian", pos: "MF" },
    { name: "Emmanuel Petit", pos: "MF" },
    { name: "Christian Karembeu", pos: "MF" },
    { name: "Stéphane Guivarc'h", pos: "FW" },
    { name: "Thierry Henry", pos: "FW" },
    { name: "David Trezeguet", pos: "FW" },
    { name: "Christophe Dugarry", pos: "FW" },
  ],

  JPN_2002: [
    { name: "Yoshikatsu Kawaguchi", pos: "GK" },
    { name: "Seigo Narazaki", pos: "GK" },
    { name: "Hitoshi Sogahata", pos: "GK" },
    { name: "Yutaka Akita", pos: "DF" },
    { name: "Naoki Matsuda", pos: "DF" },
    { name: "Ryuzo Morioka", pos: "DF" },
    { name: "Toshihiro Hattori", pos: "DF" },
    { name: "Kōji Nakata", pos: "DF" },
    { name: "Tsuneyasu Miyamoto", pos: "DF" },
    { name: "Junichi Inamoto", pos: "MF" },
    { name: "Hidetoshi Nakata", pos: "MF" },
    { name: "Hiroaki Morishima", pos: "MF" },
    { name: "Alessandro Santos", pos: "MF" },
    { name: "Takashi Fukunishi", pos: "MF" },
    { name: "Shinji Ono", pos: "MF" },
    { name: "Mitsuo Ogasawara", pos: "MF" },
    { name: "Tomokazu Myojin", pos: "MF" },
    { name: "Kazuyuki Toda", pos: "MF" },
    { name: "Daisuke Ichikawa", pos: "MF" },
    { name: "Akinori Nishizawa", pos: "FW" },
    { name: "Masashi Nakayama", pos: "FW" },
    { name: "Takayuki Suzuki", pos: "FW" },
    { name: "Atsushi Yanagisawa", pos: "FW" },
  ],

  BRA_2002: [
    { name: "Marcos", pos: "GK" },
    { name: "Dida", pos: "GK" },
    { name: "Rogério Ceni", pos: "GK" },
    { name: "Cafu", pos: "DF" },
    { name: "Lúcio", pos: "DF" },
    { name: "Roque Júnior", pos: "DF" },
    { name: "Edmílson", pos: "DF" },
    { name: "Roberto Carlos", pos: "DF" },
    { name: "Juliano Belletti", pos: "DF" },
    { name: "Ânderson Polga", pos: "DF" },
    { name: "Júnior", pos: "DF" },
    { name: "Ricardinho", pos: "MF" },
    { name: "Gilberto Silva", pos: "MF" },
    { name: "Rivaldo", pos: "MF" },
    { name: "Ronaldinho", pos: "MF" },
    { name: "Kléberson", pos: "MF" },
    { name: "Vampeta", pos: "MF" },
    { name: "Juninho Paulista", pos: "MF" },
    { name: "Kaká", pos: "MF" },
    { name: "Ronaldo Nazário", pos: "FW" },
    { name: "Denílson", pos: "FW" },
    { name: "Edílson", pos: "FW" },
    { name: "Luizão", pos: "FW" },
  ],

  GER_2014: [
    { name: "Manuel Neuer", pos: "GK" },
    { name: "Ron-Robert Zieler", pos: "GK" },
    { name: "Roman Weidenfeller", pos: "GK" },
    { name: "Kevin Großkreutz", pos: "DF" },
    { name: "Matthias Ginter", pos: "DF" },
    { name: "Benedikt Höwedes", pos: "DF" },
    { name: "Mats Hummels", pos: "DF" },
    { name: "Erik Durm", pos: "DF" },
    { name: "Philipp Lahm", pos: "DF" },
    { name: "Per Mertesacker", pos: "DF" },
    { name: "Jérôme Boateng", pos: "DF" },
    { name: "Shkodran Mustafi", pos: "DF" },
    { name: "Sami Khedira", pos: "MF" },
    { name: "Bastian Schweinsteiger", pos: "MF" },
    { name: "Mesut Özil", pos: "MF" },
    { name: "Julian Draxler", pos: "MF" },
    { name: "Toni Kroos", pos: "MF" },
    { name: "Mario Götze", pos: "MF" },
    { name: "Christoph Kramer", pos: "MF" },
    { name: "André Schürrle", pos: "FW" },
    { name: "Lukas Podolski", pos: "FW" },
    { name: "Miroslav Klose", pos: "FW" },
    { name: "Thomas Müller", pos: "FW" },
  ],

  ARG_2022: [
    { name: "Franco Armani", pos: "GK" },
    { name: "Gerónimo Rulli", pos: "GK" },
    { name: "Emiliano Martínez", pos: "GK" },
    { name: "Juan Foyth", pos: "DF" },
    { name: "Nicolás Tagliafico", pos: "DF" },
    { name: "Gonzalo Montiel", pos: "DF" },
    { name: "Germán Pezzella", pos: "DF" },
    { name: "Marcos Acuña", pos: "DF" },
    { name: "Cristian Romero", pos: "DF" },
    { name: "Nicolás Otamendi", pos: "DF" },
    { name: "Lisandro Martínez", pos: "DF" },
    { name: "Nahuel Molina", pos: "DF" },
    { name: "Leandro Paredes", pos: "MF" },
    { name: "Rodrigo De Paul", pos: "MF" },
    { name: "Exequiel Palacios", pos: "MF" },
    { name: "Thiago Almada", pos: "MF" },
    { name: "Papu Gómez", pos: "MF" },
    { name: "Guido Rodríguez", pos: "MF" },
    { name: "Alexis Mac Allister", pos: "MF" },
    { name: "Enzo Fernández", pos: "MF" },
    { name: "Julián Álvarez", pos: "FW" },
    { name: "Lionel Messi", pos: "FW" },
    { name: "Ángel Di María", pos: "FW" },
    { name: "Ángel Correa", pos: "FW" },
    { name: "Paulo Dybala", pos: "FW" },
    { name: "Lautaro Martínez", pos: "FW" },
  ],

};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { REAL_ROSTERS };
}
